# build stage
FROM node:16-alpine AS development
ARG MYSQL_HOST
ENV MYSQL_HOST=$MYSQL_HOST
ARG USER
ENV MYSQL_USER=$MYSQL_USER
ARG PASSWORD
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ARG DBNAME
ENV MYSQL_DBNAME=$MYSQL_DBNAME
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
CMD ["npm","run", "start"]