version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'devcode_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3300:3306
    expose:
      - 3300
    networks:
      - webnet
    volumes:
      - my-db:/var/lib/mysql
  
  main:
    container_name: main
    build:
      context: .
      target: development
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
    - 3030:3030
    environment:
      - PORT=3030
    command: sh -c "npm run build && npm run start"
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mysql
networks:
  webnet:
volumes:
  my-db:
